#!/bin/bash
PREFIX=$1
function run_suite {
	SUITE=$PREFIX/$1
	CLEAN=1 run-test --tap $SUITE/Setup.php
	run-suite $SUITE --tap
}

run_suite Callflow/Device
run_suite Callflow/User
run_suite Callflow/Parking
run_suite Callflow/RingGroup
run_suite Callflow/QuickCall
run_suite Callflow/Voicemail
